# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Add_new_roads
                                 A QGIS plugin
 Add new roads to roads_lat_lon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-15
        copyright            : (C) 2020 by Maria Sarajinskaya
        email                : sarajjmaria@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Add_new_roads class from file Add_new_roads.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Add_new_roads import Add_new_roads
    return Add_new_roads(iface)
